Repository ads-unigrade-2019-1/API, pull requests merged in 2019-05, with the labels that each got.

#18 TF 3.6 PESQUISA POR DISCIPLINAS
  src/controllers/SearchController.js
  src/routes.js
Labels: Tarefa

#21 Criação de scripts de Deploy e CI
  .eslintrc.json
  .travis.yml
  Dockerfile
  heroku.yml
  package.json
  src/controllers/ClassController.js
  src/controllers/CourseController.js
  src/controllers/DisciplineController.js
  src/controllers/HabilitationController.js
  src/controllers/SearchController.js
  src/index.js
Labels: Tarefa

#23 Fixed bug in Class attribute discipline
  src/models/Class.js
Labels: Bug

#25 Tf3.7 mount class schedule
  Dockerfile
  package.json
  src/algorithm/GeneticAlgorithm.js
  src/algorithm/Restrictions/ClassesIncludedRestriction.js
  src/algorithm/Restrictions/CompatibilityRestriction.js
  src/algorithm/Restrictions/HardRestriction.js
  src/algorithm/Restrictions/Restriction.js
  src/algorithm/Restrictions/RestrictionComposite.js
  src/algorithm/Restrictions/SoftRestriction.js
  src/algorithm/TimeTable.js
  src/controllers/TimetableController.js
  src/routes.js
Labels: Tarefa

#30 Changed discipline attribute structure
  src/models/Habilitation.js
Labels: Refatoração
